version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dccheck_app
    restart: always
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: administrator
      DB_PASSWORD: "Arabika1927"
      DB_NAME: dccheck
      SESSION_SECRET: fe5cae864dfd8e1445580fdd5b1c5f9e
      PORT: "3001"
      HOSTNAME: "0.0.0.0"
    volumes:
      - dccheck_uploads:/app/public/uploads
    depends_on:
      db:
        condition: service_started
    networks:
      - dccheck_net

  db:
    image: postgres:15-alpine
    container_name: dccheck_postgres
    restart: always
    environment:
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: "Arabika1927"
      POSTGRES_DB: dccheck
    ports:
      - "0.0.0.0:3002:5432"
    volumes:
      - dccheck_pgdata:/var/lib/postgresql/data
    networks:
      - dccheck_net

volumes:
  dccheck_pgdata:
  dccheck_uploads:


networks:
  dccheck_net:
    driver: bridge
