blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/torpedoliar/DataGuard/discussions
  - name: Documentation
    url: https://github.com/torpedoliar/DataGuard#readme
