import crypto from "node:crypto";

// Ticket 13 — simplify per-site NCM setup to ONE form + auto-managed webhook.
// Answers the user's efficiency complaint: one API key is indeed enough (the
// scoped admin key), and the HMAC secret is GENERATED BY DG (crypto random),
// then pushed to NCM — NCM never generates it; it only verifies.

export function generateWebhookSecret(): string {
    return crypto.randomBytes(32).toString("base64url"); // 43 chars, URL-safe
}

/** The ingest URL DG advertises to NCM, derived from env (no user typing). */
export function resolveIngestUrl(): string {
    const raw =
        process.env.DG_PUBLIC_URL ??
        process.env.NEXT_PUBLIC_APP_URL ??
        "";
    const base = raw.trim().replace(/\/+$/, "");
    if (!base) return "";
    return `${base}/api/ncm/ingest`;
}

const DG_SCOPES = [
    "read",
    "switches:write",
    "credentials:write",
    "schedules:write",
    "baselines:write",
    "backup:write",
    "reviews:write",
    "system:write",
] as const;

/** The exact scope list DG's client needs (shown in the UI as guidance). */
export function requiredDgScopes(): string[] {
    return [...DG_SCOPES];
}

/**
 * Ticket 14 — a 403 "API key lacks required scope" from NCM almost always
 * means the key predates the scopes feature (legacy key, scopes=NULL).
 * DG-side fix is operator guidance: update the key's scopes in NCM (API Keys).
 */
export function withNcmScopeGuidance(message: string): string {
    return `${message} — Key NCM Anda legacy/limited: butuh scope ${requiredDgScopes().join(", ")}. Perbarui scope key di NCM (API Keys), lalu coba lagi.`;
}
